routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'dashboard'], function () {
	Route::resource('/websites', 'WebsitesController');
	Route::resource('/categories', 'CategoriesController');
	Route::resource('/links', 'LinksController');
	Route::resource('/item-schema', 'ItemSchemaController');
	Route::resource('/articles', 'ArticlesController');
});

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    
	protected $table = 'links';
	
	public function category()
	{
		return $this->belongsTo('App\Category', 'category_id');
	}
	
	public function website()
	{
		return $this->belongsTo('App\Website', 'website_id');
	}
	
	public function itemSchema()
	{
		return $this->belongsTo('App\ItemSchema', 'item_schema_id');
	}
	
}

app/Http/Controllers/LinksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Lib\Scraper;
use App\ItemSchema;
use Goutte\Client;
use App\Category;
use App\Website;
use App\Link;

class LinksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $links = Link::orderBy('id', 'DESC')->paginate(10);
        $itemSchemas = ItemSchema::all();
        return view('dashboard.link.index', [$links, $itemSchemas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $websites = Website::all();
        return view('dashboard.link.create', [$categories, $websites]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'url' => 'required',
            'main_filter_selector' => 'required',
            'website_id' => 'required',
            'category_id' => 'required'
        ]);

        $link = new Link;
        $link->url = $request->input('url');
        $link->main_filter_selector = $request->input('main_filter_selector');
        $link->website_id = $request->input('website_id');
        $link->category_id = $request->input('category_id');
        $link->save();

        return redirect()->route('links.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $websites = Website::all();
        return view('dashboard.link.edit')
                    ->withLink(Link::find($id))
                    ->withCategories($categories)
                    ->withWebsites($websites);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'url' => 'required',
            'main_filter_selector' => 'required',
            'website_id' => 'required',
            'category_id' => 'required'
        ]);

        $link = Link::find($id);
        $link->url = $request->input('url');
        $link->main_filter_selector = $request->input('main_filter_selector');
        $link->website_id = $request->input('website_id');
        $link->category_id = $request->inputy('category_id');
        $link->save();

        return redirect()->route('links.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @param  Request $request 
     */
    public function setItemSchema(Request $request)
    {
        if (!$request->item_schema_id && !$request->link_id) {
            return;
        }

        $link = Link::find($request->link_id);
        $link->item_schema_id = $request->item_schema_id;
        $link->save();

        return response()->json(['msg' => 'Link updated!']);
    }

    /**
     * scrape specific link
     * 
     * @param  Request $request
     */
    public function scrape(Request $request)
    {
        if (!$request->link_id)
            return;

        $link = Link::find($request->link_id);
        if (empty($link->main_filter_selector) && (empty($link->item_schema_id) || $link->item_schema_id == 0)) {
            return;
        }

        $scraper = new Scraper(new Client());
        $scraper->handle($link);

        if ($scraper->status == 1) {
            return response()->json(['status' => 1, 'msg' => 'Scraping done']);
        } else {
            return response()->json(['status' => 2, 'msg' => $scraper->status]);
        }
        
    }


}

resources/views/dashboard/link/index.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Links</h2>
            <div class="alert alert-success" style="display: none"></div>
			<a href="{{ route('links.create') }}" class="btn btn-warning pull-right">Add new</a>
			@if(count($links) > 0)
				<table class="table table-bordered">
					<tr>
						<td>Url</td>
						<td>Main Filter Selector</td>
						<td>Website</td>
						<td>Assigned To Category</td>
                        <td><strong>Item Schema</strong></td>
                        <td><strong>Scrape Link</strong></td>
                        <td>Actions</td>
					</tr>
					@foreach($links as $link)
						<tr data-id="{{ $link->id }}">
							<td>{{ $link->url }}</td>
							<td>{{ $link->main_filter_selector }}</td>
                            <td>{{ $link->website->title }}</td>
                            <td><strong><span class="label label-info">{{ $link->category->title }}</span></strong></td>
                            <td>
                                <select class="item_schema" data-id="{{ $link->id }}" data-original-schema="{{ $link->item_schema_id }}">
                                    <option value="" disabled selected>Select</option>
                                </select>
                            </td>
						</tr>
					@endforeach
				</table>
				@if(count($websites) > 0)
					<div class="pagination">
						{{ $websites->render() }}
					</div>
				@endif
				@else
					<i>No websites found</i>
				@endif
		</div>
	</div>
@endsection