routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'dashboard'], function () {
	Route::resource('/websites', 'WebsitesController');
	Route::resource('/categories', 'CategoriesController');
	Route::resource('/links', 'LinksController');
	Route::resource('/item-schema', 'ItemSchemaController');
	Route::resource('/articles', 'ArticlesController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    
	protected $table = 'category';
	
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cats = Category::orderBy('id', 'DESC')->paginate(10);
		return view('dashboard.category.index')->withCategories($cats);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'title' => 'required'
		]);
		
		$cat = new Category;
		$cat->title = $request->input('title');
		$cat->save();
		
		return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('dashboard.category.edit')->withCategory(Category::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
			'title' => 'required'
		]);
		
		$cat = Category::find($id);
		$cat->title = $request->input('title');
		$cat->save();
		
		return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/category/create.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Add Category</h2>
			@if(session('error') != '')
				<div class="alert alert-danger">
					{{ session('error') }}
				</div>
			@endif
			@if(count($errors) > 0)
				<div class="alert alert-danger">
					<ul>
						@foreach($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			<form method="post" action="{{ route('categories.store') }}" enctype="multipart/form-data">
				@csrf
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Title:</strong>
							<input type="text" name="title" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 text-center">
					<button type="submit" class="btn btn-primary" id="btn-save">Create</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/dashboard/category/edit.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Update Category #{{ $category->id }}</h2>
			@if(session('error') != '')
				<div class="alert alert-danger">
					{{ session('error') }}
				</div>
			@endif
			@if(count($errors) > 0)
				<div class="alert alert-danger">
					<ul>
						@foreach($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			<form method="post" action="{{ route('categories.update', ['id' => $category->id]) }}" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Title:</strong>
							<input type="text" name="title" value="{{ $category->title }}" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 text-center">
					<button type="submit" class="btn btn-primary" id="btn-save">Update</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/dashboard/category/index.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Categories</h2>
			<a href="{{ route('categories.create') }}" class="btn btn-warning pull-right">Add new</a>
			@if(count($categories) > 0)
				<table class="table table-bordered">
					<tr>
						<td>Title</td>
						<td>Actions</td>
					</tr>
					@foreach($categories as $cat)
						<tr>
							<td>{{ $cat->title }}</td>
							<td>
								<a href="{{ url('dashboard/categories/' . $cat->id . '/edit') }}">
									<i class="glyphicon glyphicon-edit"></i>
								</a>
							</td>
						</tr>
					@endforeach
				</table>
				@if(count($categories) > 0)
					<div class="pagination">
						<?php echo $categories->render(); ?>
					</div>
				@endif
				@else
					<i>No categories found</i>
				@endif
		</div>
	</div>
@endsection