routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'dashboard'], function () {
	Route::resource('/websites', 'WebsitesController');
	Route::resource('/categories', 'CategoriesController');
	Route::resource('/links', 'LinksController');
	Route::resource('/item-schema', 'ItemSchemaController');
	Route::resource('/articles', 'ArticlesController');
});

app/Website.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Website extends Model
{
    
	protected $table = 'website';
	
}

app/Http/Controllers/WebsitesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Website;

class WebsitesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $websites = Website::orderBy('id', 'DESC')->paginate(10);
		return view('dashboard.website.index')->withWebsites($websites);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.website.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'title' => 'required',
			'url' => 'required',
			'logo' => 'required'
		]);
		
		$website = new Website;
		$website->title = $request->input('title');
		$website->url = $request->input('url');
		$website->logo = $this->uploadFile('logo', public_path('uploads/'), $request)["filename"];
		$website->save();
		
		return redirect()->route('websites.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('dashboard.website.edit')->withWebsite(Website::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
			'title' => 'required',
			'url' => 'required'
		]);
		
		$website = Website::find($id);
		$website->title = $request->input('title');
		$website->url = $request->input('url');
		
		if($request->file('logo') != null) {
			$website->logo = $this->uploadFile('logo', public_path('uploads/'), $request)["filename"];
		}
		
		$website->save();
		
		return redirect()->route('websites.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/website/create.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Add Website</h2>
			@if(session('error') != '')
				<div class="alert alert-danger">
					{{ session('error') }}
				</div>
			@endif
			@if(count($errors) > 0)
				<div class="alert alert-danger">
					<ul>
						@foreach($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			<form method="post" action="{{ route('websites.store') }}" enctype="multipart/form-data">
				@csrf
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Title:</strong>
							<input type="text" name="title" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Url:</strong>
							<input type="text" name="url" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Logo:</strong>
							<input type="file" name="logo" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 text-center">
					<button type="submit" class="btn btn-primary" id="btn-save">Create</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/dashboard/website/edit.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Update Website #{{ $website->id }}</h2>
			@if(session('error') != '')
				<div class="alert alert-danger">
					{{ session('error') }}
				</div>
			@endif
			@if(count($errors) > 0)
				<div class="alert alert-danger">
					<ul>
						@foreach($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			<form method="post" action="{{ route('websites.update', ['id' => $website->id]) }}" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Title:</strong>
							<input type="text" name="title" value="{{ $website->title }}" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Url:</strong>
							<input type="text" name="url" value="{{ $website->url }}" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
                    @if($website->logo != "")
                        <img src="{{ url('uploads/' . $website->logo) }}" width="150" />
                    @endif
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Logo:</strong>
							<input type="file" name="logo" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 text-center">
					<button type="submit" class="btn btn-primary" id="btn-save">Update</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/dashboard/website/index.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Websites</h2>
			<a href="{{ route('websites.create') }}" class="btn btn-warning pull-right">Add new</a>
			@if(count($websites) > 0)
				<table class="table table-bordered">
					<tr>
						<td>Title</td>
						<td>Logo</td>
						<td>Url</td>
						<td>Actions</td>
					</tr>
					@foreach($websites as $website)
						<tr>
							<td>{{ $website->title }}</td>
							<td><img width="150" src="{{ url('uploads/' . $website->logo) }}" /></td>
							<td><a href="{{ $website->url }}">{{ $website->url }}</a></td>
							<td>
								<a href="{{ url('dashboard/websites/' . $website->id . '/edit') }}">
									<i class="glyphicon glyphicon-edit"></i>
								</a>
							</td>
						</tr>
					@endforeach
				</table>
				@if(count($websites) > 0)
					<div class="pagination">
						{{ $websites->render() }}
					</div>
				@endif
				@else
					<i>No websites found</i>
				@endif
		</div>
	</div>
@endsection