routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'dashboard'], function () {
	Route::resource('/websites', 'WebsitesController');
	Route::resource('/categories', 'CategoriesController');
	Route::resource('/links', 'LinksController');
	Route::resource('/item-schema', 'ItemSchemaController');
	Route::resource('/articles', 'ArticlesController');
});

app/ItemSchema.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ItemSchema extends Model
{
    
	protected $table = 'item_schema';
	
}

app/Http/Controllers/ItemSchemaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ItemSchema;

class ItemSchemaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $itemSchema = ItemSchema::orderBy('id', 'DESC')->paginate(10);
        return view('dashboard.item_schema.index')->withItemSchemas($itemSchema);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.item_schema.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'css_expression' => 'required',
            'full_content_selector' => 'required'
        ]);

        $itemSchema = new ItemSchema;
        $itemSchema->title = $request->input('title');
        
        if ($request->input('is_full_url') != null) {
            $itemSchema->is_full_url = 1;
        } else {
            $itemSchema->is_full_url = 0;
        }

        $itemSchema->css_expression = $request->input('css_expression');
        $itemSchema->full_content_selector = $request->input('full_content_selector');
        $itemSchema->save();

        return redirect()->route('item-schema.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('dashboard.item_schema.edit')->withItemSchema(ItemSchema::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'css_expression' => 'required',
            'full_content_selector' => 'required'
        ]);

        $itemSchema = ItemSchema::find($id);
        $itemSchema->title = $request->input('title');

        if ($request->input('is_full_url') != null) {
            $itemSchema->is_full_url = 1;
        } else {
            $itemSchema->is_full_url = 0;
        }

        $itemSchema->css_expression = $request->input('css_expression');
        $itemSchema->full_content_selector = $request->input('full_content_selector');
        $itemSchema->save();

        return redirect()->route('item-schema.index');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/item_schema/create.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Add Item Schema</h2>
			@if(session('error') != '')
				<div class="alert alert-danger">
					{{ session('error') }}
				</div>
			@endif
			@if(count($errors) > 0)
				<div class="alert alert-danger">
					<ul>
						@foreach($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			<form method="post" action="{{ route('item-schema.store') }}" enctype="multipart/form-data">
				@csrf
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Title:</strong>
							<input type="text" name="title" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>CSS Expression:</strong>
							<input type="text" name="css_expression" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Is Full Url To Article/Partial Url:</strong>
							<input type="checkbox" name="is_full_url" value="1" checked>
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Full content selector:</strong>
							<input type="text" name="full_content_selector" class="form-control" />
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 text-center">
					<button type="submit" class="btn btn-primary" id="btn-save">Create</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/dashboard/item_schema/edit.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Update Item Schema #{{ $itemSchema->id }}</h2>
			@if(session('error') != '')
				<div class="alert alert-danger">
					{{ session('error') }}
				</div>
			@endif
			@if(count($errors) > 0)
				<div class="alert alert-danger">
					<ul>
						@foreach($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif
			<form method="post" action="{{ route('item-schema.update', ['id' => $itemSchema->id]) }}" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Title:</strong>
							<input type="text" name="title" value="{{ $itemSchema->title }}" class="form-control">
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>CSS Expression:</strong>
							<input type="text" name="css_expression" value="{{ $itemSchema->css_expression }}" class="form-control">
                            <div class="help-block">CSS expression identifies css selector for specific item in a single article separated by ||. i.e. h2.post_title for title</div>
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Is Full Url To Article/Partial Url:</strong>
							<input type="checkbox" name="is_full_url" value="1" {{ $itemSchema->is_full_url ? "checked" : "" }}>
						</div>
					</div>
				</div>
                <div class="row">
					<div class="col-xs-12 col-sm-12 col-md-6">
						<div class="form-group">
							<strong>Full content selector:</strong>
							<input type="text" name="full_content_selector" value="{{ $itemSchema->full_content_selector }}" class="form-control">
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 text-center">
					<button type="submit" class="btn btn-primary" id="btn-save">Update</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/dashboard/item_schema/index.blade.php
@extends('layout')

@section('content')
	<div class="row">
		<div class="col-md-12">
			<h2>Item Schema</h2>
			<a href="{{ route('item-schema.create') }}" class="btn btn-warning pull-right">Add new</a>
			@if(count($itemSchemas) > 0)
				<table class="table table-bordered">
					<tr>
						<td>Title</td>
						<td>CSS Expression</td>
						<td>Is Full Url To Article</td>
						<td>Actions</td>
					</tr>
					@foreach($itemSchemas as $item)
						<tr>
							<td>{{ $item->title }}</td>
                            <td>{{ $item->css_expression }}</td>
                            <td>{{ $item->is_full_url == 1 ? "Yes" : "No" }}</td>
                            <td>{{ $item->full_content_selector }}</td>
                            <td>
                                <a href="{{ url('dashboard/item-schema/' . $item->id . '/edit') }}">
                                    <i class="glyphicon glyphicon-edit"></i>
                                </a>
                            </td>
						</tr>
					@endforeach
				</table>
				@if(count($itemSchemas) > 0)
					<div class="pagination">
						{{ $itemSchemas->render() }}
					</div>
				@endif
				@else
					<i>No items found</i>
				@endif
		</div>
	</div>
@endsection